### ISSUE TITLE
userInfo 有什么用？

### ISSUE THREAD

**Issue by ZsIsMe** [Aster0id/YCXMenuDemo_ObjC#1]
- (instancetype)menuItem:(NSString *)title image:(UIImage *)image tag:(NSInteger)tag userInfo:(NSDictionary *)userInfo；
  我看一下源码 ，发现这个userInfo好像没用，这个userInfo有什么意义？

**Comment by Aster0id** [comment]
UserInfo是NSDictionary类型, 可以自定义一些数据放到字典中进行传递.
类似- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo中userinfo的存在
