### ISSUE TITLE
如何设置item内部的图片和文字左对齐，以及如何让item之间的分割线的宽度与view的宽度相同啊

### ISSUE THREAD

**Issue by ZYVIP** [Aster0id/YCXMenuDemo_ObjC#11]
如何设置item内部的图片和文字左对齐，以及如何让item之间的分割线的宽度与view的宽度相同啊
![qq20160801-0 2x](https://cloud.githubusercontent.com/assets/20380063/17282194/048f4e4e-57d6-11e6-9fec-c325af6eefaa.png)

**Comment by Aster0id** [comment]
1.最新版已经是item之间的分割线的宽度与view的宽度相同了
2.还没有支持item内部的图片和文字左对齐，不过也不难写，你可以尝试修改，提交Fork

**Comment by ZYVIP** [comment]
恩，谢谢博主了，我一直没更新过。不过已经解决了，谢谢了
